name: Test

on: [push]

jobs:
  test-job:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: awscli
        uses: hannut91/aws-cli@1.18.43
        with:
          args: --version
